# Custom Language File for Launcher Customizer

[ejs.app]
title = "Nour Launcher"

[ejs.landing]
mediaWebsiteURL = "https://discord.gg/nouroni"
mediaTwitterURL = "https://discord.gg/nouroni"
mediaInstagramURL = "https://discord.gg/nouroni"
mediaYouTubeURL = "https://discord.gg/nouroni"
mediaDiscordURL = "https://discord.gg/nouroni"

[ejs.settings]
sourceGithubLink = "https://github.com/Muspelheim-Hosting/NourLauncher"
supportLink = "https://discord.gg/nouroni"

[ejs.welcome]
welcomeHeader = "WELCOME TO NOUR LAUNCHER"
welcomeDescription = "You are using the Nour Launcher, this launcher was made by Albert & Tyr"
welcomeDescCTA = "Come on! You are just a few clicks away from joining Nour's Realm!"
